name: "Site Studio CI"
on:
  push:
    branches: [ main, 7.*.* ]
  pull_request:
    branches: [ main, 7.*.* ]

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.5', '10']
        php-versions: ['8.0', '8.1']

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
          COHESION_VERSION: 7.0.x
          DRUPAL_VERSION: ${{ matrix.drupal-core }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
