name: "Site Studio CI"
on:
  push:
    branches: [ main, 7.*.* ]
  pull_request:
    branches: [ main, 7.*.* ]

jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drupal-core: ['9.5', '10']
        php-versions: ['8.0', '8.1']

    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
          COHESION_VERSION: 7.0.x
          DRUPAL_VERSION: ${{ matrix.drupal-core }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COH_API_KEY: ${{ secrets.COH_API_KEY }}
          COH_ORG_KEY: ${{ secrets.COH_ORG_KEY }}
          COH_API_URL: https://eu-development-api.sitestudio.acquia.com
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DRUPAL_USER: admin
          DRUPAL_PWD: admin
          BUILD_ID: ${{ GITHUB_RUN_ID }}
          BUILD_NUMBER: ${{ GITHUB_RUN_NUMBER }}

      - name: Run our scripts
        run: |
          docker compose exec -T web bash ./run.sh
